//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPMuhiarov.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BookAuthors = new HashSet<BookAuthors>();
            this.BookLoans = new HashSet<BookLoans>();
            this.BookRestorations = new HashSet<BookRestorations>();
        }
    
        public int BookId { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string GenreName { get; set; }
        public Nullable<int> PublicationYear { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> PageCount { get; set; }
        public string Annotation { get; set; }
        public string Language { get; set; }
        public string ConditionName { get; set; }
        public string StatusName { get; set; }
        public decimal WearPercentage { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Location { get; set; }
        public int BranchId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthors> BookAuthors { get; set; }
        public virtual BookConditions BookConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookLoans> BookLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookRestorations> BookRestorations { get; set; }
        public virtual Branches Branches { get; set; }
        public virtual BookStatuses BookStatuses { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
