//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPMuhiarov.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLoans
    {
        public int LoanId { get; set; }
        public Nullable<int> ReaderId { get; set; }
        public Nullable<int> BookId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime PlannedReturnDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Fine { get; set; }
        public Nullable<int> LibrarianId { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Librarians Librarians { get; set; }
        public virtual Readers Readers { get; set; }
    }
}
