//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPMuhiarov.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibrarianSchedules
    {
        public int ScheduleId { get; set; }
        public Nullable<int> LibrarianId { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Librarians Librarians { get; set; }
    }
}
