//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPMuhiarov.MVVM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YPMuhiarovEntities : DbContext
    {
        public YPMuhiarovEntities()
            : base("name=YPMuhiarovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BookAuthors> BookAuthors { get; set; }
        public virtual DbSet<BookConditions> BookConditions { get; set; }
        public virtual DbSet<BookLoans> BookLoans { get; set; }
        public virtual DbSet<BookRestorations> BookRestorations { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BookStatuses> BookStatuses { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Librarians> Librarians { get; set; }
        public virtual DbSet<LibrarianSchedules> LibrarianSchedules { get; set; }
        public virtual DbSet<ReaderCategories> ReaderCategories { get; set; }
        public virtual DbSet<Readers> Readers { get; set; }
    }
}
